FROM mcr.microsoft.com/dotnet/core/sdk:3.1

RUN mkdir src
WORKDIR /src
ADD . /src
RUN dotnet restore
RUN ["dotnet", "build", "--configuration", "release"]

EXPOSE 5001

ENV ASPNETCORE_URLS="http://+:5001"
ENV ASPNETCORE_ENVIRONMENT="Production"

ENTRYPOINT [ "dotnet", "run", "--no-launch-profile" ]